ALTER TABLE "GameProfile"
ADD COLUMN "companionId" TEXT NOT NULL DEFAULT 'nova_fox',
ADD COLUMN "readAloud" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "speechRate" DOUBLE PRECISION NOT NULL DEFAULT 0.9;
