import Head from "next/head";
import Link from "next/link";
import styles from "./Policy.module.css";

export default function PrivacyNotice() {
  return <div className={styles.page}>
    <Head><title>Privacy Notice · StudySmart</title><meta name="description" content="How StudySmart handles K–12 learner and family data." /></Head>
    <header className={styles.hero}><p className={styles.eyebrow}>Versioned public notice</p><h1>Privacy Notice</h1><p>StudySmart is designed to collect only the information needed to provide, protect, and improve a K–12 learning service.</p><p className={styles.meta}>Effective July 16, 2026 · Notice version 2026-07-k12-v2</p></header>
    <div className={styles.notice}><strong>Preview launch gate:</strong> Before accepting public users, the deploying organization must add its legal name, postal address, privacy contact, jurisdiction-specific notices, and counsel-approved consent language.</div>
    <section className={styles.section}><h2>Information collected</h2><ul><li>Account identifiers supplied through authentication, such as email and display name.</li><li>An age group and grade level; StudySmart does not ask learners for a birth date.</li><li>Courses, learning goals, uploaded or pasted study material, tutor history when enabled, quiz and study evidence, mastery signals, and game progress.</li><li>Guardian, teacher, classroom, consent, safety, and accessibility settings needed for the requested features.</li><li>Payment status from Stripe. StudySmart does not store complete card numbers.</li><li>Privacy-safe operational records. Prompts, uploads, passwords, cookies, tokens, contact details, and raw child content are excluded from operational logs.</li></ul></section>
    <section className={styles.section}><h2>How information is used</h2><ul><li>Provide source-grounded tutoring, practice, games, accessibility, progress, and scheduled review.</li><li>Enforce age, guardian-consent, district, content-safety, and security controls.</li><li>Deliver urgent safety notifications to authorized connected adults.</li><li>Operate, secure, troubleshoot, and measure the reliability of the service.</li></ul><p>StudySmart does not use child information for targeted advertising or sell it. Optional learner-linked product analytics are off by default.</p></section>
    <section className={styles.section}><h2>AI and school use</h2><p>AI access for an under-13 learner requires the configured parental or school authorization path. Uploaded materials are treated as untrusted source data and responses identify whether they use uploaded material or general knowledge. A school deployment must define who has a legitimate educational interest and control StudySmart’s use and maintenance of education records in its written agreement.</p></section>
    <section className={styles.section}><h2>Sharing and service providers</h2><p>Information is shared only for requested service operations, authorized guardian/teacher views, school-controlled use, safety, legal obligations, or a business transfer subject to applicable protections. Current provider categories and purposes are listed on the <Link href="/subprocessors">Subprocessors page</Link>.</p></section>
    <section className={styles.section}><h2>Retention and deletion</h2><p>Learners can choose 30, 90, or 365 days for tutor and uploaded-content retention; a shorter district limit wins. Encrypted safety-alert details use a separately configured short retention period. Account holders can export data and request correction, restriction, or deletion from the Trust Center. Backups follow the separately documented backup lifecycle and must not be retained indefinitely.</p></section>
    <section className={styles.section}><h2>Parents, guardians, and data rights</h2><p>Authorized parents and guardians can review connected learner progress and consent status. Account holders can download a machine-readable export and submit correction, restriction, or deletion requests in the <Link href="/trust">Trust Center</Link>. The operator must verify the requester before releasing or deleting child information.</p></section>
    <section className={styles.section}><h2>Security and questions</h2><p>StudySmart uses authenticated access checks, encryption for sensitive alert details, no-store responses for protected data, rate limits, audit events, retention enforcement, and monitored health checks. Security reports can be submitted privately through the <Link href="/security">Security page</Link>. The final production operator privacy contact will be published before public launch.</p></section>
  </div>;
}
