import Head from "next/head";
import Link from "next/link";
import styles from "./Policy.module.css";

export default function TermsOfService() {
  return <div className={styles.page}>
    <Head><title>Terms of Service · StudySmart</title><meta name="description" content="Terms for using the StudySmart K–12 learning service." /></Head>
    <header className={styles.hero}><p className={styles.eyebrow}>Versioned public terms</p><h1>Terms of Service</h1><p>These terms explain the rules for using StudySmart as a learner, parent, guardian, teacher, or school.</p><p className={styles.meta}>Effective July 18, 2026 · Terms version 2026-07-k12-v1</p></header>
    <div className={styles.notice}><strong>Public-launch gate:</strong> The deploying organization must add its legal name, postal address, support contact, governing law, jurisdiction-specific consumer terms, and counsel approval before accepting public users or payments.</div>
    <section className={styles.section}><h2>Who may use StudySmart</h2><p>StudySmart serves K–12 learning. A child may use the service only through the age-appropriate parent, guardian, or school authorization provided in the product. A parent or guardian must make purchases for a minor. Users must provide accurate account information and keep sign-in credentials private.</p></section>
    <section className={styles.section}><h2>Learning service, not professional advice</h2><p>StudySmart provides educational practice, tutoring, games, and progress insights. AI responses can be incomplete or incorrect, so learners and adults should verify important information against class materials and trusted educators. StudySmart is not medical, mental-health, legal, or emergency advice. Anyone facing immediate danger should contact local emergency services or a trusted adult.</p></section>
    <section className={styles.section}><h2>Acceptable use and learner safety</h2><p>Users may not seek or share sexual, violent, hateful, abusive, illegal, self-harm instructional, or otherwise age-inappropriate content; bully or threaten others; evade safety controls; impersonate another person; compromise accounts or systems; or use the service to cheat in violation of school rules. Safety controls may block content, preserve a limited safety record, notify authorized connected adults, limit access, and support a review or appeal as described in the <Link href="/privacy">Privacy Notice</Link>.</p></section>
    <section className={styles.section}><h2>Uploaded material</h2><p>Users keep ownership of material they are permitted to upload. They give StudySmart a limited license to store, process, transform, and display that material only as needed to provide, secure, and improve the requested service. Users must have permission to upload the material and must not upload confidential information they are not authorized to share.</p></section>
    <section className={styles.section}><h2>Paid plans and AI usage</h2><p>Paid plans renew monthly until canceled. The checkout page shows the current price, included AI credits, and beneficiary learner before purchase. Different AI features use different credit amounts because their processing costs differ. StudySmart does not silently charge overage fees: when a monthly allowance is used, paid AI features pause until renewal or a plan change. Customers may manage or cancel an active plan through the billing portal; cancellation normally takes effect at the end of the paid period. Taxes, refunds, and statutory cancellation rights follow the checkout terms and applicable law.</p></section>
    <section className={styles.section}><h2>Schools, classrooms, and guardians</h2><p>Teachers, guardians, and school administrators may access learner information only when authorized and for a legitimate educational or safety purpose. Schools remain responsible for notices, permissions, account administration, and education-record obligations assigned to them by law or contract. Classroom game codes must be shared only with intended participants.</p></section>
    <section className={styles.section}><h2>Availability and account action</h2><p>Features may change as the service improves. StudySmart may restrict or suspend access to protect learners, users, or the service; respond to illegal activity; enforce these terms; or comply with law. When appropriate, the account holder can request a review through the Trust Center. Users may stop using the service and request account deletion subject to necessary safety, billing, fraud-prevention, and legal retention.</p></section>
    <section className={styles.section}><h2>Privacy, accessibility, and support</h2><p>The <Link href="/privacy">Privacy Notice</Link> explains data handling. Accessibility commitments appear on the <Link href="/accessibility">Accessibility page</Link>, and security reporting appears on the <Link href="/security">Security page</Link>. Final operator contact information will be published before public launch.</p></section>
    <section className={styles.section}><h2>Disclaimers and responsibility</h2><p>To the extent permitted by applicable law, the service is provided without a promise that every answer, recommendation, or feature will be error-free or always available. Nothing in these terms limits rights or liability that cannot legally be limited. Final warranty, liability, dispute, and governing-law language must be approved for the production operator and its jurisdictions before public launch.</p></section>
  </div>;
}
