ALTER TABLE "LearnerProfile"
ADD COLUMN "dailyReviewLimit" INTEGER NOT NULL DEFAULT 20;

ALTER TABLE "Flashcard"
ADD COLUMN "nextReviewAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "lastReviewedAt" TIMESTAMP(3),
ADD COLUMN "intervalDays" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "easeFactor" DOUBLE PRECISION NOT NULL DEFAULT 2.5,
ADD COLUMN "scheduledReviewCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "lapseCount" INTEGER NOT NULL DEFAULT 0;

CREATE INDEX "Flashcard_userId_nextReviewAt_idx"
ON "Flashcard"("userId", "nextReviewAt");
